services:
  backend:
    build: ./backend
    ports:
      - "8567:8567"
    env_file:
      - .env
    volumes:
      - ./backend:/app
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "3567:80"
    volumes: # auto-refresh the localhost on file saves 
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - backend
    restart: unless-stopped